In [6]:
import numpy as np


In [7]:
a1 = np.arange(5)
a2 = np.arange(stop=11,start=6)
print(a1,a2)
print(a1.dot(a2))

[0 1 2 3 4] [ 6  7  8  9 10]
90


In [11]:
print("finding inverse of array:::")
multi_d = np.arange(16).reshape(4,4)
print(multi_d)
print(multi_d.ndim)
# inverse
# print(np.linalg.inv(multi_d))
# determinant
print(np.linalg.det(multi_d))
# diagnoal product
print(np.diag(multi_d))

finding inverse of array:::
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2
0.0
[ 0  5 10 15]


In [37]:
a = np.arange(7)
b = a[:,None]
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
# we can combine two matrices or arrays using vstack and hstack
a1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.array([[1,2,3],[4,5,6]]).T)
a2 = np.array([[10,11,12]])
print(a2.T)
print(np.concatenate((a1,a2.T),axis=1))
# print(np.vstack((a1,a2)))

[[1 4]
 [2 5]
 [3 6]]
[[10]
 [11]
 [12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
